name: unityspace
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  crop_your_image: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.3.0
  lottie: ^3.1.2
  phone_numbers_parser: ^8.3.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  string_validator: ^1.1.0
  url_launcher: ^6.2.6
  window_manager: ^0.3.9
  wstore: ^1.0.3

dev_dependencies:
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/notifications/
    - assets/animations/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic

flutter_launcher_icons:
  ios: true
  android: true
  macos:
    generate: true
  windows:
    generate: true
  remove_alpha_ios: true
  image_path: assets/images/unityspace_logo.png

flutter_native_splash:
  ios: true
  android: true
  color: "#212022"
  image: assets/images/unityspace_logo_256.png
